### ISSUE TITLE
[Feature request] rename `Factory type` to `Ohshown Event Type`

### ISSUE THREAD

**Issue by tai271828** [tai271828/disfactory-backend#11]
**Describe the solution you'd like**
Please fix this wording shown below in the django admin site:

![Selection_560](https://user-images.githubusercontent.com/3217432/145211525-48c72052-4746-443d-8a4a-0d0c4a340936.png)

**Additional context**
Relates to #9 and #1

**Comment by EagleC0318** [comment]
Would you have any idea in your mind about what's the Ohshown Event Type?
Is it something like BEAR_TRACE, BEAR_SEEN?
Maybe we can change the dropped-down list value as well.

**Comment by diaoga** [comment]
> Would you have any idea in your mind about what's the Ohshown Event Type? Is it something like BEAR_TRACE, BEAR_SEEN? Maybe we can change the dropped-down list value as well.

Hi eagle, I have leave some suggestion at issue [#14](https://github.com/tai271828/disfactory-backend/issues/14)

**Comment by diaoga** [comment]
> Hi @EagleC0318 , the name was decided in the meetup last Wednesday. A name or prefix for a specific animal may be suggested because we are aim at a "cross-species" platform.
> 
Hello Tai, I tried to draw a sketchup for cross-species use and find it could be very complicated....
Need more time to figure it out.

**Comment by tai271828** [comment]
@diaoga  no worries. That is expected. If you or anyone have ideas regarding how the flow of a "cross-species" service and architecture should be, you may be interested in putting the comments and information in this "Github discussion thread" https://github.com/tai271828/disfactory-backend/discussions/17 .


> > Hi @EagleC0318 , the name was decided in the meetup last Wednesday. A name or prefix for a specific animal may be suggested because we are aim at a "cross-species" platform.
> 
> Hello Tai, I tried to draw a sketchup for cross-species use and find it could be very complicated.... Need more time to figure it out.

**Comment by tai271828** [comment]
Close as the corresponding PR has landed.
