### ISSUE TITLE
Create Ohshown event type API

### ISSUE THREAD

**Issue by tai271828** [tai271828/disfactory-backend#22]
**Is your feature request related to a problem? Please describe.**
We have had issue #15 , and this may be resolved by API for the frontend so the frontend does not need to hard-coded its draw-down list for event types.

**Describe the solution you'd like**
`api/get_event_types` or something

**Describe alternatives you've considered**
Any solution that could help the flow to share the same event type model between backend and frontend may be sufficient.

**Additional context**
Issue #15

**Comment by EagleC0318** [comment]
@tai271828 we already had this kinda API endpoint via https://github.com/tai271828/disfactory-backend/pull/18.
But I remember the FE people said that they current need to have the list when initialized the FE instance, and they can't call the API endpoint at that time.

**Comment by tai271828** [comment]
Good catch. You are right. Thanks for the reminder! Track in the frontend instead now https://github.com/tai271828/disfactory-frontend/issues/50

> @tai271828 we already had this kinda API endpoint in this PR #18. But I remember the FE people said that they current need to have the list when initialized the FE instance, and they can't call the API endpoint at that time.
