### ISSUE TITLE
[Feature request] rewording factory to ohshown in django admin site

### ISSUE THREAD

**Issue by tai271828** [tai271828/disfactory-backend#9]
By clicking one of the entries in the django admin site, for example, `admin/api/factory/<instance UUID>/change/`, the wording `factory` should be renamed as `ohshown` or the other names that fit in our use case.

For example,

![Selection_560](https://user-images.githubusercontent.com/3217432/145211525-48c72052-4746-443d-8a4a-0d0c4a340936.png)

In `admin/api`
![Selection_561](https://user-images.githubusercontent.com/3217432/145211675-c6cc0173-0ae3-4f65-bc49-ff032adc45aa.png)

Please note any refactoring that we performed should keep the the data model as-is. That being said, it could be written into DB and reused by the django admin site:

![Selection_562](https://user-images.githubusercontent.com/3217432/145211811-fd521469-bcc9-4ed3-91b8-693831d1c6a2.png)

**Comment by diaoga** [comment]
Hi there!  Here is my suggestion for Backend API rewording

**Disfactory-->OHSHOWN-->(Note)**
Cet nexts-->(maybe this item could be delete)
Cet report statuss-->Species Check	
Documents-->Feedback(未來聯繫通報者的欄位)
Factorys-->OhShown Events
Follow ups-->(keep it)
Gov response statuss-->(maybe this item could be delete)
Images-->Images and videos
Questionnaire-->(New feature in the future)
Recycled factorys-->Recycled Events
Recycled images-->Recycled images and videos
Recycled report records-->(keep it)
Report records-->(keep it)

**Comment by diaoga** [comment]
**Factorys --> Hoshown Events**

**Cet review status -->Review Status**
- 尚未審查
- 已審查, 臺灣黑熊(資料完整)
- 已審查, 需進一步聯繫(資料不完整)
**Cet report status -->Species check**
- 是臺灣黑熊
- 不是臺灣黑熊
- 其他物種(或許可以羅列其他常見物種，另開放一個自由填寫的欄位?)
- 無法確定
**Building status --> Report type**
- 目擊黑熊
- 發現痕跡
**Usage status --> Attributes**
- 目擊黑熊
- 發現痕跡
- 人熊衝突
- 救傷事件

**Details**
"Landcode, Sectname, Sectcode, Name" --> These field could be delete

**Other fields we will need:**
- Altitude 
- Description of encounter place(發現地點描述)
- Encounter date and time

**Comment by diaoga** [comment]
Maybe "Questionnaire" could be a new feature in backend API?

**Comment by tai271828** [comment]
Wow, thanks @diaoga . Your information really helps!

**Comment by tai271828** [comment]
Move this comment to discussion https://github.com/tai271828/disfactory-backend/issues/9#issuecomment-998590500 and close this issue as the corresponding PR has been merged.

**Comment by tai271828** [comment]
The discussion thread https://github.com/tai271828/disfactory-backend/discussions/25
